version: '3.4'

services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  apigw:
    image: ${DOCKER_REGISTRY-}apigw
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw/Dockerfile
    depends_on:
      - cip.api
      - dt.api

  cip.api:
    image: ${DOCKER_REGISTRY-}cipapi
    build:
      context: .
      dockerfile: src/Services/CIP/CIP.API/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq
      
  dt.api:
    image: ${DOCKER_REGISTRY-}dtapi
    build:
      context: .
      dockerfile: src/Services/DT/DT.API/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq